config/routes.rb
Rails.application.routes.draw  do
  post 'email_from_personal_page', to: "responses#email"

  root :to => "questions#root_page"


  get 'users/random', :to => "users#random_sign_up"
  resources :users, only: [:new, :create, :index, :show]

  get 'questions/top', :to => "questions#top"
  get 'questions/unanswered', :to => "questions#unanswered"
  resources :questions

  resources :responses, only: [:create]

  get 'auth/:provider/callback', to: 'sessions#omniauth_callback'
  get 'auth/failure', to: redirect('/')
  resource :sessions, only: [:new, :create, :destroy]
  get 'sessions/search', :to => "sessions#search"

  get 'api_questions/search', :to => "api_questions#search"
  resources :api_questions, only: [:index, :show, :create], defaults: { :format => 'json' } do
    resources :api_responses, only: [:index], defaults: { :format => 'json' }
  end

  resources :api_users, only: [:index, :show], defaults: { :formant => 'json'}
  patch 'api_users/', to: 'api_users#update_current_user'
  put  'api_users/', to: 'api_users#update_current_user'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :user_id, :title, presence: true
  validate :title_less_than_255
  before_save :sanitize

  attr_accessor :responds

  belongs_to :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  has_many :responses


def self.top25
  select("questions.*, count(responses.id) AS response_count")
  .joins(:responses)
  .group("questions.id")
  .order("response_count DESC")
  .limit(25)
end



private
  def title_less_than_255
    if self.title.length > 255
      self.errors.add(:title, "is too long")
    end
  end

  def sanitize
    self.title = Sanitize.fragment(self.title)
    self.body = Sanitize.fragment(self.body,
    :elements => ['b','u','i','img','ul','li','font','div','font','ol','style','br','h1','h2','h3','h4','h5','h6'],
    :attributes =>
      {:all => ['color', 'style', 'background-color','size', 'face', 'src','href']},
    :css =>
      {:properties => ['background-color','text-align','color']})
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :redirect_logged_in, only:[:create, :unanswered, :show, :index, :top]
  before_action :redirect_not_logged_in, only:[:root_page]

  def root_page
    render :root_page
  end

  def index
    @questions = Question.includes(:responses).all.order('id DESC').limit(25).offset(sanitize_page) #sorted by reverse created
    render :index
  end

  def top
    @questions = Question.top25.offset(sanitize_page)
    render :top
  end

  def unanswered
    @questions = Question.all.where(best_answer_id: nil).limit(25)
    render :unanswered
  end

  def show
    @question = Question.find(params[:id])
    @responses = Response.includes(:user).where(question_id: @question.id)
    render :show
  end

  def new
    redirect_to new_sessions_url
  end

private

  def redirect_not_logged_in
    if !logged_in?
      redirect_to questions_top_url
    end
  end

  def clean_params
    params.require(:question).permit(:title, :body)
  end


end

app/views/questions/_question_list.html.erb
<ul <ul class="question-index-true" >
<% @questions.each do |question| %>
  <li> <strong class="count bestReplay-false">
  <%=question.responses.length%> <b>answers</b>
  </strong>
  <a class="question" href="<%=question_url(question)%>"> <%= question.title%></a>
  <strong class="author" >
    <img src="<%=question.user.avatar.url(:thumb)%>"> <%=question.user.username%></img>
  </strong>

  </li>
<% end %>
</ul>

app/views/questions/index.html.erb
<h1>top questions</h1>

<ul>
<% @questions.each do |question| %>
<section>
  <h2> <%= question.title %>
    <strong> ........ asked by, <%=question.user.username%> </strong>
  </h2>
</secion>
<% end %>
</ul>

app/views/questions/new.html.erb
<form action="<%=questions_url%> " method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="title">Title
    <input type="textarea" name="question[title]">
  </label>
  <br>
  <label for="body">Body
    <input type="text" name="question[body]">
  </label>
  <br>
  <button>submit question</button>
</form>

app/views/questions/show.html.erb
<section class="question-show-title">
  <h1>  <%= @question.title %> </h1>

  <p>
  <%= @question.body.html_safe %>
  </p>
  <div class="question-show-author-tag"> <a href="<%=user_url(@question.user)%>"><img src="<%=@question.user.avatar.url(:thumb)%>" width=35> <%= @question.user.username %> </div>
</section>


<ul class="question-show-responses">
  <% @responses.each do |resp| %>
  <li>
  <p>
    <%=resp.body%>
  </p>
  <div class="question-show-author-tag">
  <a href="<%=user_url(resp.user)%>"> <img src="<%=resp.user.avatar.url(:thumb)%>" width=35> <%= resp.user.username %></a>
  </div>
  </li>
  <% end %>
</ul>


<h2>your Answer</h2>
<form action=" <%=new_sessions_url%> " method="get">
  <label for="body">Response
<textarea name="" cols="60" rows="5" tabindex="101" data-min-length=""></textarea>

  </label>
  <br>
  <button>Log in to Post</button>
</form>

app/views/questions/top.html.erb
<h1>Top Questions</h1>


<%= render partial: "question_list" %>

app/views/questions/unanswered.html.erb
<h1>Unanswered Questions</h1>


<%= render partial: "question_list" %>