config/routes.rb
Rails.application.routes.draw  do
  post 'email_from_personal_page', to: "responses#email"

  root :to => "questions#root_page"


  get 'users/random', :to => "users#random_sign_up"
  resources :users, only: [:new, :create, :index, :show]

  get 'questions/top', :to => "questions#top"
  get 'questions/unanswered', :to => "questions#unanswered"
  resources :questions

  resources :responses, only: [:create]

  get 'auth/:provider/callback', to: 'sessions#omniauth_callback'
  get 'auth/failure', to: redirect('/')
  resource :sessions, only: [:new, :create, :destroy]
  get 'sessions/search', :to => "sessions#search"

  get 'api_questions/search', :to => "api_questions#search"
  resources :api_questions, only: [:index, :show, :create], defaults: { :format => 'json' } do
    resources :api_responses, only: [:index], defaults: { :format => 'json' }
  end

  resources :api_users, only: [:index, :show], defaults: { :formant => 'json'}
  patch 'api_users/', to: 'api_users#update_current_user'
  put  'api_users/', to: 'api_users#update_current_user'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :username, :provider, presence: true

  validates :email, :username, uniqueness: {scope: :provider, message: "only one unique user per sign in provider"}

  validate :valid_email, :password_length
  attr_reader :password, :avatar

  before_save :generate_session_token, :sanitize

  def self.find_by_login(params)
    user = User.find_by(username: params[:username])
    return nil if !user
    if BCrypt::Password.new(user.password_digest).is_password?(params[:password])
      return user
    end
    nil
  end

  def self.from_omniauth(auth)
      @user = User.find_by(auth_token: auth.credentials.token)
      return @user if @user

      @user = User.find_by(uid: auth.uid)
      if @user
        @user.auth_token = auth.credentials.token
        @user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        return @user
      end
      @user = User.new
      @user.fname= auth.extra.raw_info.given_name
      @user.lname= auth.extra.raw_info.family_name
      @user.email= auth.extra.raw_info.email
      @user.username = @user.email.split("@")[0]
      @user.provider = auth.provider
      @user.uid = auth.uid
      @user.auth_token = auth.credentials.token
      @user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      @user.password = SecureRandom.urlsafe_base64(8)
      return @user
  end


  has_many :questions,
  class_name: "Question",
  foreign_key: :user_id,
  primary_key: :id

  has_many :responses,
  class_name: "Responses",
  foreign_key: :user_id,
  primary_key: :id


  has_attached_file :avatar, :default_url => ":style/missing.jpg", :styles => { :medium => "256x256>", :thumb => "50x50>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/





  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

    def generate_session_token
        self.session_token = SecureRandom.urlsafe_base64(16)
        self.session_token
    end

  private
    def valid_email
      if !(self.email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i)
        self.errors.add(:email, "must be in proper format")
      end
    end

    def password_length
      if !(@password.nil? || @password.length > 5)
        self.errors.add(:password, "must be at least 6 characters")
      end
    end

    def sanitize
      self.username = Sanitize.fragment(self.username)
      self.fname = Sanitize.fragment(self.fname)
      self.lname = Sanitize.fragment(self.lname)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_logged_in

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def random_sign_up
    @names = "Velvet Banks,Lemon Jello,Richard Cox,Justin Case,Lighten up,Ronald McDonald,Neit Ballsack,Norman Bates,Quentin Quale,Jeeves Wooster,Snooki Prince,Dick Less,Hives Butler,Molly Warmflash,Pussy Galore,Tiffany Case,Holly Goodhead,Monly Jones,Bawana Fana,Draco Malfoy,Andreas Gimli,Bella Buttcheeks,Buzz Lightyear,Harry Wang,San Juniper,Ben Purr,Bonly Stuart,Robert Roberts,Bong Queesha,Gypsy Starblanket,Mary McDonald,Billy Bob,Harry Glands".split(",")
    name = @names.sample.split(" ")

    username = "pip_longstocking" + rand(999).to_s
    @user = User.new(username: username, email: username+"@email.com", fname: name[0], lname: name[1] )
    @user.password = "password"
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      self.login(@user)
      redirect_to root_path
    else
      flash.now[:errors]=@user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @questions = Question.where(user_id: @user.id)
    @resps = Response.includes(:question).where(user_id: @user.id)
    render :show
  end

 private
  def user_params
    params[:user][:avatar] = params[:user][:avatar2] if params[:user][:avatar].nil?
    params.require(:user).permit(:email, :username, :fname, :lname, :password, :avatar)
  end

end

app/views/users/_index.html.erb
<ul>

<li><a href="#">Ask a question</a> </li>
<li><a href="<%= user_questions_url(current_user) %>">View your questions</a></li>

</ul>

app/views/users/index.html.erb
<div class="users-index-list group">
  <% @users.each do |user| %>
      <section>

          <a href="<%=user_url(user)%>">
            <img src="<%=user.avatar.url(:thumb)%>">
            <strong> <%=user.username%></strong>
            <ul>
              <li>name: <%=user.fname%></li>
              <li>member since: </li>
              <li> <%=user.created_at.to_s[0..10]%></li>
            </ul>
          </a>
      </section>

  <%  end %>
  </div>

app/views/users/new.html.erb
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" >
  </script>
<h1>sign up!</h1>

<ul>
<% flash[:errors].to_a.each do |error| %>
  <li> <%=error%> </li>
<% end %>
</ul>

<a id="make-random-user" href="/users/random">Make Random User</a>

<form id="new_user" action="<%=users_url%>" enctype="multipart/form-data" method="post"  accept-charset="UTF-8">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">email
  <input type="text" name="user[email]" value="<%=@user.email%>">
  </label>
  <br>
  <label for="username">username
  <input type="text" name="user[username]" value="<%=@user.username%>">
  </label>
  <br>
  <label for="password">password</label>
  <input type="password" name="user[password]" value="<%=@user.password%>">
  </label>
  <br>
  <button>Submit</button>
  <br>
  <br> Tell us more! <br>
  <br>
  <label for="fname">First Name</label>
  <input type="text" name="[user]fname" value="<%=@user.fname%>">
  <br>
  <label for="lname">Last Name</label>
  <input type="text" name="[user]lname" value="<%=@user.lname%>">
  <br>

  <label for="user[avatar]">upload profile image</label>
  <input type="file" name="user[avatar]" id="user_avatar">
  <label>..or use random cute cat picture</label>
  <input type="url" name="user[avatar2]" id="user_avatar2" value="http://loremflickr.com/320/240">
  <br>
  <img id="avatar" src="" alt="" width=100/>
  <br>
  <button>Submit</button>

</form>

  <script type="text/javascript">
  var readURL = function(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function(e) {
          $("#avatar").attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $("input[type=file]").change(function(){
        readURL(this);
    });
  </script>

  <div id="goog-signin">
  or  <a href="/auth/google_oauth2">sign up with <img src="http://mashable.com/wp-content/uploads/2007/06/logo-google.thumbnail.gif"/></a>
  </div>

app/views/users/show.html.erb
<section class="profile">

  <img class="profile-image" src="<%=asset_path(@user.avatar.url(:medium))%>"/>

  <article class="about">
    <h2> <%=@user.username%> </h2>
    <ul>
       <% if !@user.fname.nil? %>
      <li> <%=@user.fname%> </li>
        <% end %>
    </ul>
    <p>

    </p>
  </article>
  </section>
  <section class="activity"> </section>
  <section class="edit-profile"> </section>
  <section class="history">

      <h1 class="user-show-tab-title questions-tab group in-front">Questions</h1>
      <!-- <h1 class="user-show-tab-title answers-tab group in-back">Answers</h1> -->
      <div class="asked">
        <div>
        <ul class="question-index-false in-front questions-tab">
            <% @questions.each do |question|%>
            <li>
              <a class="question" href="/questions/<%=question.id%>"><%=question.title%></a>
            </li>
            <% end %>
        </ul>
      </div>
    </div>

  </section>