config/routes.rb
Rails.application.routes.draw  do
  post 'email_from_personal_page', to: "responses#email"

  root :to => "questions#root_page"


  get 'users/random', :to => "users#random_sign_up"
  resources :users, only: [:new, :create, :index, :show]

  get 'questions/top', :to => "questions#top"
  get 'questions/unanswered', :to => "questions#unanswered"
  resources :questions

  resources :responses, only: [:create]

  get 'auth/:provider/callback', to: 'sessions#omniauth_callback'
  get 'auth/failure', to: redirect('/')
  resource :sessions, only: [:new, :create, :destroy]
  get 'sessions/search', :to => "sessions#search"

  get 'api_questions/search', :to => "api_questions#search"
  resources :api_questions, only: [:index, :show, :create], defaults: { :format => 'json' } do
    resources :api_responses, only: [:index], defaults: { :format => 'json' }
  end

  resources :api_users, only: [:index, :show], defaults: { :formant => 'json'}
  patch 'api_users/', to: 'api_users#update_current_user'
  put  'api_users/', to: 'api_users#update_current_user'

end

app/views/layouts/_nav_bar.html.erb
<ul class="nav-bar group">
  <li class="logo"><a href="#"><img src="<%=asset_path("logo2.png")%>"> NYstack<strong>exchange</strong></a></li>
  <ul class="nav-bar-paths">
  <li><a href="<%=questions_url%>">Questions</a></li>
  <li><a href="<%=users_url%>">Users</a></li>
  <li><a href="<%=questions_unanswered_url%> ">Unanswered</a></li>
  <li><a href="<%= new_question_url%>">Ask Question</a></li>
  </ul>
</ul>

app/views/layouts/_top_black_bar.html.erb
<div class="just-black group">
<header class="black-bar group">


    <input id="drop-down" type="checkbox">
      <ul class="stack-exchange">
        <label for="drop-down"><img src=<%=asset_path("se-icon.png")%> alt=""/> StackExchange</label>
        <li><a class="links" href="http://stackexchange.com/"><img class="se-icon" src=<%=asset_path("se-icon.png")%> alt=""/> <i class="white-text">Stack</i><b class="blue">Exchange</b></a></li>
        <li><a class="links" href="http://stackoverflow.com/"><img class="se-icon" src=<%=asset_path("so-icon.png")%> alt=""/> Stack<b>Overflow</b></a></li>
        <li>
          <a href="http://stackexchange.com/sites"> more communities..</a></li>
      </ul>

  <ul class="header-options">
    <li>
      <% if logged_in? %>
        <a  href="<%=user_url(current_user)%>"><img class="thumb" height=30 src="<%=asset_path(current_user.avatar.url(:thumb))%>"></a>
      <% else %>
        <a  href="<%=new_user_url%>">sign up</a>
      <% end %>
    </li>
    <%= render partial: "codeBin/logout" %>

    <li class="no-login visible">
      <a href="<%=new_sessions_url%>">log in</a>
    </li>

    <li></li>

    <li>
      <ul class="help" >
        <li>help</li>
        <li>tour</li>
        <li>help center</li>
        <li>meta</li>
      </ul>
    </li>

    <li>
      <form class="search-bar" action="<%=sessions_search_url%>" method="get">
        <input  class="search-bar-box" type="text" name="search" placeholder="search">
        <button style = "display:none"></button>
      <div id="live-search-results">

      </div>
      </form>
    </li>

  </ul>


</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow-NYC</title>
  <% if !logged_in? %>
    <script>
      if (window.location.hash){
          window.location.replace(window.location.origin+"/" +window.location.hash.slice(1))}
    </script>
  <% else %>
      <%= javascript_include_tag 'application', :type => "text/javascript"%>
  <% end %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <script src="//js.nicedit.com/nicEdit-latest.js" type="text/javascript"> </script>


</head>



<body>
  <%= render partial: "layouts/top_black_bar" %>
  <%= render partial: "layouts/nav_bar" %>



  <div class="content">
    <%= yield %>

  </div>

  <%
  "
  todo

  add best answer selection
  add best answer hoist and display

  add voting
  display votes

  add edit pages

  duplicate static pages

  css
  set up my server to ping

  refactor
  google auth to konrad-dudziak

  remove project breakdowns


  fix links under questions

  fix all links on question page
  "
   %>

</body>
</html>